name: projekt_pdf
on: push

jobs: 
  pdf:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - uses: actions/checkout@v4
      - run: |
          pip install \
            numpy \
            matplotlib \
            pint \
            open-atmos-jupyter-utils \
            scipy \
            nbconvert \
            ipykernel \
            pympdata \
            pillow
      - run: |
          python -m nbconvert \
            --to pdf \
            --execute projekt_shallow_water_stok_przybrzezny.ipynb \
            --output projekt.pdf
      - uses: actions/upload-artifact@v4 
        with:
          path: projekt.pdf
